### ISSUE TITLE
sourcing different uc: bluepill

### ISSUE THREAD

**Issue by zoobab** [davidgiven/fluxengine#4] opened 2019-02-19 17:56 UTC
"Sourcing a different microcontroller. The PSoC5 is a great thing to work with, but it’s disappointingly proprietary and the toolchain only works on Windows. It’d be nice to support something easier to work with. I need a 5V microcontroller (which unfortunately rules out Arduinos) with at least seventeen GPIO pins in a row. As non-PSoC5 microcontrollers won’t have the FPGA soft logic, that also means I’d most likely need to bitbang the floppy drive, so speed is important. If you have any recommendations, please get in touch."

I think the stm32 bluepill has enough GPIOs, here it says it has 32 GPIOs:

https://os.mbed.com/users/hudakz/code/STM32F103C8T6_Hello/

It runs in 3.3V, I guess it would be possible to run in 5V as well,  to be checked.

**Comment by zoobab** [comment] 2019-02-19 18:38
On the same page, the 5V input tolerant pins are also indicated, I counted 22 of them. I don't know if you also need 5V output pins as well.

**Comment by roybaer** [comment] 2019-02-19 19:10
Looks like you beat me by a couple of minutes!
But I was quicker, anyway, because I already have custom hardware: #5 :-P

**Comment by davidgiven** [comment] 2019-02-19 19:39
You'd need 5V output pins in order to be able to control the drive. I don't know if the standard board has pullup resistors --- probably not, I'm guessing.

The only place it has 17 pins in a row is on the right-hand side, and one of those isn't 5V tolerant. Depending which way up you put the connector that's either /MOTEA (motor enable drive A, output) or /TRK00 (track 0 detect, input).

72MHz should be plenty fast enough to sample the disk but I don't know whether it's fast enough to sample the disk while also doing 1MB/s USB I/O --- sorry, don't have the experience here.

Instant judgement: promising, but would probably need a custom (and therefore expensive) board with external components, and you'd need to talk to someone who knows about the STM32 to know whether it can handle the load.

**Comment by davidgiven** [comment] 2019-02-19 19:41
...although now I think of it, all the control lines on the drive are active low. I bet they have their own pull-up resistors. Hmm.

**Comment by zoobab** [comment] 2019-02-19 19:46
Someone is saying 1MB/sec here:

https://stackoverflow.com/questions/44275560/what-is-the-maximum-speed-of-the-stm32-usb-cdc

But other comments says 500ko/sec depending on the library used.

**Comment by davidgiven** [comment] 2019-02-19 21:22
I didn't think I'd get fast enough using CDC, so instead I'm using a custom bulk endpoint. USB is terrible, but it actually wasn't too bad once I realised all the limitations. I'm comfortably getting 900kB/s, which is sufficient. (If you've built a FluxEngine, fe-testbulktransport will do a USB bandwidth test.)

The thing is, the PSoC5 can let the processor handle all the USB stuff because the sampling is happening in 'hardware' and so not consuming any CPU load.

My sample clock is 12MHz, so for a 72MHz device that's one bit every 6 cycles. Tough but probably just doable with hand-tooled assembly but I'm not sure it could do anything else at the same time!

**Comment by swarren** [comment] 2019-02-20 15:37
I haven't looked at the code, but a thought based on the previous comment:

Have you thought about sampling using interrupts on GPIO edges rather than polling every n cycles? That might reduce CPU load etc., at the risk of introducing latency. Some microcontrollers can capture timing information on IRQs or GPIO edges, so the edge to IRQ Handley latency wouldn't be an issue.

**Comment by swarren** [comment] 2019-02-20 15:43
Or use something like an SPI peripheral with DMA to capture the raw pulse train to RAM.

**Comment by davidgiven** [comment] 2019-02-20 16:42
Re interrupts: an HD disk can have a pulse every 1-2 us. The PSoC does this in 'hardware', where a pulse causes capture of the timer and then the capture value is pushed to the DMA system to be written to memory without any CPU involvement. The timer runs at 12MHz and needs to be as accurate as possible --- on the PSoC the timer clock is derived from the 48MHz USB crystal; anything else had too much jitter.

My statement above that it's one bit every six cycles was wrong --- I'd mixed up the sample clock and bit rate. It's actually 72 cycles, which is enough to get work done, but is still not much.

What's the Arduino interrupt latency like? I can't find any figures.

**Comment by davidgiven** [comment] 2019-07-07 22:40
Duplicate of: #5

**Closed by davidgiven** 2019-07-07 22:40 UTC
