### ISSUE TITLE
Amiga Write Issues

### ISSUE THREAD

**Issue by andrewferguson** [davidgiven/fluxengine#202] opened 2021-01-02 21:53 UTC
I was fiddling around with my Amiga 500 today and on a whim, decided I'd try out Fluxengine's Amiga disk support. I imaged my Amiga 500's workbench (boot) disk, and it was successfully read. (I tested the image using the FS-UAE emulator and it booted fine in that). I then tried to write that same image out to a second disk, and boot the Amiga off that, but it didn't like it. (Rejected the disk after a couple of seconds). There weren't any errors reported when Fluxengine was writing the disk.

I completely understand if your reaction to this is "the chap [with the macs](https://github.com/davidgiven/fluxengine/issues/73) that kept pestering me last year has Amigas too?!", so no obligations to look into this - just thought I'd alert you to the (potential) issue.

I also recall that the reason you couldn't investigate writing Mac 800k disks was because you don't have a suitably old Mac to try things with, so that issue will likely be the same here.

But if there's anything I can do to help you test / debug this issue, please let me know. Frustratingly, there seems to be an issue with my Amiga where left-click doesn't work (even through the keyboard shortcut), so I can't actually *use* the Amiga OS to format / duplicate images for testing. I'm guessing this will somewhat limit the usefulness of having actual hardware, if all I can do is image boot disks and say if they work or not. (It's probably something stupid I'm doing - I'm not an Amiga person, in fact, today was the first time I'd properly set it up since getting it).

**Comment by davidgiven** [comment] 2021-01-03 20:37
I do actually have a classic Mac now, but haven't done anything with 800kB drives because... um... apathy? And, TBH, my time's been going to another project recently.

I'm not surprised that the Amiga disk writer isn't working; it's never been tested. It'd be good to sort this out. (I am actually looking for an Amiga 600 of my own, for various projects and also games...) The good news is that the Amiga disk format is simple, with only really one big 'sector', and it's capable of reading a semi-raw image of a disk containing the entire MFM data dump using, I think, this: http://aminet.net/package/disk/bakup/rawread So debugging out to be relatively simple --- read an Amiga disk to an ADF, write it back, compare the raw MFM dumps of the two.

I'm not an Amiga person either but I _believe_ that most of the OS is in ROM and the Workbench floppy mostly contains the GUI. I know it's possible to get to an AmigaDOS prompt fairly easily, somehow...

**Comment by ivanizag** [comment] 2021-04-17 11:55
I have looked at this doing a read, write and read again. There are many read errors on the inner tracks. It may be the lack of precompensation? I have tried uncommenting back precompensation in writeTracks() of writer.cc, but as the comment says it makes things worse.

I don't how it works to go further, but I would love being able to write Amiga disks.

**Comment by hharte** [comment] 2021-04-17 13:55
I had similar issues with writing 360K 5.25” IBM disks.  I tried several drives, and found that some drives worked better than others.  Eventually, I figured out that adjusting the drive speed to exactly 300RPM resolved the issue for problematic drives.

**Comment by bbbradsmith** [comment] 2021-11-10 09:13
I acquired a greaseweazle v4 device for comparison. I seems to be able to write valid Amiga disks for me with the same drive, same power supply, same disk media. (Greaseweazle v4 hardware, software 0.31.)

If this information is of any use, here is 3 successive flux reads using fluxengine, greaseweazle, then fluxengine again on the same disk.
* gs0 - Written with fluxengine. Doesn't read in my Amiga.
* gs1 - Written with greaseweazle. Reads and boots.
* gs2 - Written again with fluxengine. Doesn't read.

Commands used:
```
fluxengine write amiga -i enemy2a.adf
fluxengine read amiga --copy-flux-to gs0.flux - o gs0.adf
; switch to greaseweazle
gw write --drive b enemy2a.adf
; switch back to fluxengine
fluxengine read amiga --copy-flux-to gs1.flux - o gs1.adf
fluxengine write amiga -i enemy2a.adf
fluxengine read amiga --copy-flux-to gs2.flux - o gs2.adf
```

Now that I can create a workbench disk, I could see in workbench that the readable disk had a name of "ENEMY_A" and the unreadable version reported as "DF1:BAD" when placed in my second drive.

In each case the ADF reads back completely fine, so I would assume the problem has to do with the disk formatting outside the sectors?

[compare_greaseweazle.zip](https://github.com/davidgiven/fluxengine/files/7511225/compare_greaseweazle.zip)

**Comment by davidgiven** [comment] 2022-02-13 21:11
I know this is ancient and kind of forgotten about, but I've made a tonne of changes (and bugfixes). All three flux files decode correctly --- is that what you were observing when you files this?

**Comment by bbbradsmith** [comment] 2022-02-13 23:02
The problem I had wasn't decoding flux files, the problem is that my Amiga, could not read the ADF image disks written with Fluxengine. It was able to read disks written with Greaseweazle. (A500, tested with the original internal drive and an original external drive)

Fluxengine was able to read its own disks correctly, so I expect that it should be able to decode the flux readback. My assumption was that there is something different about the two formatting interpretations between what Greaseweazle and Fluxengine produce. There's likely something different between the gs1 and gs2  flux that is the source of the incompatibility.

**Comment by davidgiven** [comment] 2022-02-14 00:09
Yes, of course --- my bad (it's been too long!).

I think I've actually managed to confirm this with my setup. (I just got my Amiga working, which is why I came back to this.) It's not as severe as you're seeing, with ~1 bad sector per disk, and in earlier tests it looked like disk problems, but yeah, the Fluxengine disks seem to be less reliable.

At least with the Amiga in operation I should be able to do easier investigation. I need to find a nibble-mode disk sector editor somewhere.

**Comment by davidgiven** [comment] 2022-02-16 23:24
...and now my Amiga's keyboard matrix has died. This might be a while!

**Comment by davidgiven** [comment] 2022-03-14 22:43
After ordering a new keyboard membrane, discovering that it had been damaged in the post and getting a replacement, I finally have my Amiga working again, so looking at this.

**Comment by davidgiven** [comment] 2022-03-15 22:15
Okay, I've got something. The raw data for track 16 side 0 looks like this when read on FluxEngine:

```
000002      0.006 : aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa 
000042      0.262 : aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa 
000082      0.518 : aa aa aa 44 89 44 89 55 12 aa a5 55 2a aa a9 2a 
0000c7      0.774 : aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa 
000107      1.030 : aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa 
000147      1.286 : aa aa aa aa 92 aa a4 2a aa aa aa aa aa aa aa aa 
```

When read on the Amiga, everything else looks the same _except_ that the checksum is `aa 92 aa a5 aa aa`. 

A4 2A should be X-X--X-- --X-X-X-. A5 AA should be X-X--X-X X-X-X-X-. This suggests that the long gap is written with the wrong length and the Amiga is misdetecting it. However, when I look at the raw flux pulses, I can see that the gap lengths are either 4us, 6us or 10us, almost precisely. And I read that back with a GreaseWeazle, so it's not a FluxEngine bug in the read path.

So all I can say is that the Amiga _should_ be reading this correctly, except it's not, which is really weird. And it's completely repeatable --- no how many times I read the disk on each machine, it produces the same results.

**Comment by davidgiven** [comment] 2022-03-15 22:21
Argh. Please diregard. PEBCAK error causing me to analyse the wrong image. Sigh. I'll have to start again from scratch.

**Comment by davidgiven** [comment] 2022-03-15 23:15
Okay. Suspect checksum, as seen by a FluxEngine:

```
0049e5     70.173 : aa aa aa 44 89 44 89 55 25 2a a9 55 2a a4 a5 2a 
004a2c     70.429 : aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa 
004a6c     70.685 : aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa 
004aac     70.941 : aa aa aa aa a5 24 a4 2a aa aa aa aa aa aa aa aa 
```

The Amiga sees a checksum of a5 24 a5 aa.

The correct checksum bit pattern is X-X- -X-X / --X- -X-- / X-X- -X-- / --X- X-X-.

The Amiga's bit pattern is X-X- -X-X / --X- -X-- / X-X- -X-X / X-X- X-X-. Two Xs next to each other (in the a5 5a sequence) should never happen.

Looking at the flux sequence, the intervals end up being (lined up with the correct bit pattern):

````
A    5      2    4      A    4    2    a
X-X- -X-X / --X- -X-- / X-X- -X-- / --X- X-X- <- correct bit pattern
 4 6   4    6  6   6     4 6    9      4  4
X-X- -X-X / --X- -X-- / X-X- -X-X / X-X- X-X- <- what the Amiga sees
```

I actually get this, but I see errors of up to 10% in the pulse timings --- that _should_ be reasonable? But comparing against the Amiga bit pattern, there's definitely a stray pulse or two being seen in the middle of that 9us gap.

There is one additional piece of information: attempting to reproduce this the second time, I found myself completely unable, until I realised that I'd unplugged the second drive. So, I think that bad reads only happen when the second drive is plugged in. This suggests some kind of electrical or protocol issue with the way the FluxEngine is communicating with the drive.

**Comment by davidgiven** [comment] 2022-03-16 00:02
Right. I have a potential fix for this. It seems to make the problem go away on my hardware, but I'm seeing far fewer errors than you are. Could you install this firmware and see if it helps you? @bbbradsmith 

https://github.com/davidgiven/fluxengine/blob/inspect/FluxEngine.cydsn/CortexM3/ARM_GCC_541/Release/FluxEngine.hex

I suspect that having two drives connected adds load to the signal lines and causes the output data line to rise slowly, somehow (?) generating a weaker signal on the disk. This shouldn't happen, as the pulse is just a trigger causing the drive to invert the polarity of the generated field, but making the pulse longer _does_ seem to help on my hardware. I'd like to know if it helps anyone else.

**Closed** 2022-03-26 22:30 UTC

**Comment by bbbradsmith** [comment] 2022-03-31 19:54
I have now tested this and it seems to be working well. I have managed to write a few disk images and boot them in my Amiga.

**Comment by davidgiven** [comment] 2022-03-31 22:04
Excellent. I'll call this done, then --- thanks for testing.
