### ISSUE TITLE
decoding 5.25 inch HD floppies fails

### ISSUE THREAD

**Issue by tingox** [davidgiven/fluxengine#48] opened 2019-03-22 09:59 UTC
I have a test setup with a Teac FD-55GFR floppy drive and FluxEngine. This setup reads and decodes IBM formatted DD floppies just fine (all those floppies have a hub ring).
However, decoding of HD formatted floppies fails. Example:
`tingo@kg-bsbox:~/personal/projects/psoc/fluxengine/tmp$ ../.obj/fe-readibm -s 525-RPS-dos.flux -o 525-RPS-dos.img`
I have also tried the three most likely candidates from `--show-clock-histogram` but it still fails. I'll send you the flux file.

**Comment by davidgiven** [comment] 2019-03-22 10:09
What are you formatting the floppies on? Also, could you try putting a DD format on an HD floppy and see if that works? I've observed peculiar issues with trying to use mismatched formats.

Another thing which is worth trying: fe-writetestpattern will allow you to write evenly spaced pulses onto the disk, or at least one track of the disk, and fe-inspect will let you see these. It's worth trying different spacings to see what reads back reliably.

Assuming this is simply me not setting the density select line correctly, the fix should be simple, and I'll try and get it done this weekend. It'll need a firmware upgrade, though. Also I have no way to test this myself...

**Comment by tingox** [comment] 2019-03-22 12:09
these floppies cam with an old machine I got I have not formatted them myself. All but one fails to read data from the floppy. Example:
`tingo@kg-bsbox:~/personal/projects/psoc/fluxengine/tmp$ ../.obj/fe-readibm -o 525-RPS-unlabeled.img -f 525-RPS-unlabeled.flux`
`[..]`
`H.SS Tracks --->`
`No sectors in output; skipping analysis`
`0 tracks, 0 heads, 0 sectors, 0 bytes per sector, 0 kB total`

I have one HD floppy which I believe have a DD format on it:
`$ ../.obj/fe-readibm -s 525-CIS-pc-tools.flux -o 525-CIS-pc-tools_3.58.img --manual-clock-rate-us=3.58`
`[..]`
`H.SS Tracks --->`
`0. 0 B.......................................`
`0. 1 B......B................................`
`0. 2 ........................................`
`0. 3 ..........................X.............`
`0. 4 ........................................`
`0. 5 ........................................`
`0. 6 ........................................`
`0. 7 ........................................`
`0. 8 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB`
`1. 0 ........................................`
`1. 1 ........................................`
`1. 2 ........................................`
`1. 3 ........................................`
`1. 4 ........................................`
`1. 5 ........................................`
`1. 6 ........................................`
`1. 7 ........................................`
`1. 8 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB`
`Good sectors: 636/720 (88%)`
`Missing sectors: 1/720 (0%)`
`Bad sectors: 83/720 (11%)`
`40 tracks, 2 heads, 9 sectors, 512 bytes per sector, 360 kB total`
this might be copy protected, I don't know (it is a copy of a PC Tools floppy). I'll send you the flux file.

writing - I didn't bring any blank floppies today, so I'll try your suggestions this weekend.
Testing - I'm happy to test what I can.

**Comment by davidgiven** [comment] 2019-03-22 12:35
All the sector 8s showing up bad is very suggestive. It _could_ be that sector's straddling the index mark --- try `--revolutions=2` and see if that helps --- but having sectors with deliberately bad CRCs is a classic copy protection trick.

**Comment by tingox** [comment] 2019-03-23 20:57
good news, with the firmware and client from the "hd" branch, I can actually read 5.25 inch HD floppies.
Example:
```
tingo@kg-u35jc:~/personal/projects/psoc/fluxengine/tmp$ ../.obj/fe-readibm -o 525-CIS-dos.img -f 525-CIS-dos.img
[..]
H.SS Tracks --->
0. 0 .............................................BB.XB..XX.XBXBXXX..XXX..XX.X.XX.X..
0. 1 .............................................BB.XB..BXX.XXXXXXXXXX...X.XX.X..X..
0. 2 .............................................BB.BB..B.BXBXXXXXBXXX..BXX.X.X..X..
0. 3 .............................................BX.BX..B.XXXXXX.X.X.X...X.XX.XXX...
0. 4 .............................................BB.XX..BXXXBXXXXXXXXXX.XX.XXBXXXX..
0. 5 .............................................XX.XX..XXBXXXXXXXXXXXXX.X.XXXXXX...
0. 6 .............................................XX.XX..XXXXBXXXXXXXXXXXXXBXXXXXXX..
0. 7 .............................................XX.XX..XXXXBXXXXXBXXXXX.XXXXXXXXX..
0. 8 .............................................X..XB..BXXXBXXXXX.X.XXXXX.XXXXX.X..
0. 9 .............................................XX.XX..XXXXXX.XXX.XXXXXXXX.XXXXXX..
0.10 .............................................XX.XB..XXXXBXXXXXXXXXXXXXXXX.XXXX..
0.11 .............................................XX.XX..X.XXXXXXXX.XXXXXXXXXX.XXXX..
0.12 .............................................XX.XX..XXBXXXXXXXXXXXX.XX.XXXXXXX..
0.13 .............................................X..X...XXXXXXXXXXXXXXXX.XXXXXXXXX..
0.14 .............................................BX.XX..BXXXXXXXXXXXXXXXXXXXXXX.XX..
1. 0 ................................................................................
1. 1 ...................................................X............................
1. 2 ................................................................................
1. 3 ................................................................................
1. 4 ................................................................................
1. 5 ............................................XXX....X............................
1. 6 ..............................................X....X............................
1. 7 ............................................BXX....X............................
1. 8 ................................................................................
1. 9 ...................................................X............................
1.10 ................................................................................
1.11 ................................................................................
1.12 ................................................................................
1.13 ............................................B...................................
1.14 ............................................BB..................................
Good sectors: 1992/2400 (83%)
Missing sectors: 365/2400 (15%)
Bad sectors: 43/2400 (1%)
80 tracks, 2 heads, 15 sectors, 512 bytes per sector, 1200 kB total

```
and file says
```
tingo@kg-u35jc:~/personal/projects/psoc/fluxengine/tmp$ file 525-CIS-dos.img
525-CIS-dos.img: DOS/MBR boot sector, code offset 0x3c+2, OEM-ID "IBM  4.0", root entries 224, sectors 2400 (volumes <=32 MB), Media descriptor 0xf9, sectors/FAT 7, sectors/track 15, serial number 0x11c8233b, unlabeled, FAT (12 bit), followed by FAT
```
so it is something. It doesn't seem to matter if I use the '-H' switch or not.

**Comment by davidgiven** [comment] 2019-03-26 19:07
Turns out the `-H` flag I added was actually broken and did nothing --- the drive was stuck in DD mode. This _probably_ won't help reading 5.25" HD disks, but at least it's fixed now (in the hd branch).

**Comment by tingox** [comment] 2019-03-27 12:50
Testing with updated firmware and client from 'hd' branch. Without the --high-density flag I get buffer underrun as before (this is a 5.25 inch HD, DOS-formatted floppy):
```
tingo@kg-bsbox:~/personal/projects/psoc/fluxengine/tmp$ ../.obj/fe-readibm -o 525-RPS-dos.img -f 525-RPS-dos.flux
Reading from: :d=0:s=0-1:t=0-79
Writing a copy of the flux to 525-RPS-dos.flux
  0.0: Error: USB underrun (not enough bandwidth)

```
adding the --high-density flag and testing again
```
tingo@kg-bsbox:~/personal/projects/psoc/fluxengine/tmp$ ../.obj/fe-readibm -o 525-RPS-dos.img -f 525-RPS-dos.flux --high-density
Reading from: :d=0:s=0-1:t=0-79
Writing a copy of the flux to 525-RPS-dos.flux
  0.0: 162 ms in 100288 bytes (617 kB/s)
       1.00 us clock; 20292 bytes encoded; 30 records
       0 sectors;
       0 bytes decoded.
  0.1: 162 ms in 92288 bytes (567 kB/s)
       0.96 us clock; 21229 bytes encoded; 30 records
       0 sectors;
       0 bytes decoded.
  1.0: 162 ms in 106496 bytes (656 kB/s)
       1.00 us clock; 20264 bytes encoded; 30 records
       0 sectors;
       0 bytes decoded.
  1.1: 162 ms in 105600 bytes (651 kB/s)
       1.00 us clock; 20264 bytes encoded; 30 records
       0 sectors;
       0 bytes decoded.
[..]
 79.0: 162 ms in 88256 bytes (541 kB/s)
       1.08 us clock; 18798 bytes encoded; 9 records
       0 sectors;
       0 bytes decoded.
 79.1: 162 ms in 90880 bytes (558 kB/s)
       1.12 us clock; 18085 bytes encoded; 0 records
       0 sectors;
       0 bytes decoded.
H.SS Tracks --->
No sectors in output; skipping analysis
0 tracks, 0 heads, 0 sectors, 0 bytes per sector, 0 kB total

```
a bit strange that it doesn't decode anything?

**Comment by tingox** [comment] 2019-04-08 09:18
FWIW, using the latest firmware and client from master, the '--hd' flag results in no data being decoded. Here a 5.25 inch, HD, ms-dos formatted floppy:
```
tingo@kg-bsbox:~/personal/projects/psoc/fluxengine/tmp$ ../.obj/fe-readibm --retries=0 -o 525-Handel-dos-own-formatted.img -f 525-Handel-dos-own-formatted.flux --hd
Reading from: :d=0:s=0-1:t=0-79
Writing a copy of the flux to 525-Handel-dos-own-formatted.flux
  0.0: (49081 bytes crunched) 163 ms in 78528 bytes
       0.96 us clock; 21300 bytes encoded; 29 records
       0 sectors;
       0 bytes decoded.
  0.1: (49520 bytes crunched) 163 ms in 79232 bytes
       0.96 us clock; 21289 bytes encoded; 29 records
       0 sectors;
       0 bytes decoded.
[..]
 79.0: (54560 bytes crunched) 162 ms in 87296 bytes
       1.04 us clock; 19554 bytes encoded; 30 records
       0 sectors;
       0 bytes decoded.
 79.1: (56161 bytes crunched) 162 ms in 89856 bytes
       1.08 us clock; 18780 bytes encoded; 0 records
       0 sectors;
       0 bytes decoded.
H.SS Tracks --->
No sectors in output; skipping analysis
0 tracks, 0 heads, 0 sectors, 0 bytes per sector, 0 kB total
```
without the '--hd' flag it works, kinda
```
tingo@kg-bsbox:~/personal/projects/psoc/fluxengine/tmp$ ../.obj/fe-readibm --retries=0 -o 525-Handel-dos-own-formatted.img -f 525-Handel-dos-own-formatted.flux
[..]
H.SS Tracks --->
0. 0 .BBXBBXBBBBBBBBBBBBBBBBBBBBBXBBBBBBBB..B...BBBXBBBXBXBBXBBBBBBBBBBBBBBBXBB.BB...
0. 1 .BBBBBBBBBXBBBBBBBBBBBBBBB.BBBBBBB.B.BBBBBB.BBBBBBXBBBBBBBBXBBBBBBBBXBBBBB.X.BBB
0. 2 .BBBBBBBBBBBBBBBBBBBBBBBB.BBB.B.BXBBBB..BBB.BBBBXXBBBBXBBBBXBBBBBBBBBBBXBBBBB...
0. 3 .BBBBXBBBBBBBBBBBBBBBBBBBBBBBBBBBBXB.BB.BB.BBBBXBXBBBBXBBBBXBBBXBBBBXBBBXBB.BB.B
0. 4 .BBXBBBBBXXBBBBBBXBBBBB.BBBBBBBBBB..BBB.B...XBXBBBBBBBXXXBBBXBBBBBBBBBBBBBB.BBBB
0. 5 .BBBBXBBBBBBBBBBBXBBBBBBBBBBBBB..BB.B.B...B.BBXBBBBBBBBXBBXXBBBBBBBBBBBB.BBBBBB.
0. 6 .BBBBBBBBBBBBBBBBXBBBBXBBBBBBBBBBBBBBBB..BB.BXXXBBBBBBXXBBBBBBBBBBBBBBBXBBBBB..B
0. 7 .BBBBBXBBBBXBBBBBBBBBBBBXBBBBBBBBBB.BBB.BB.BBBXBBBBBXXXBBBBBBBBBBBBBBBBBBBBBBBB.
0. 8 .BBBBBBBBBBBBBBBBXBBBBBBBBBBBBXB.BBBBBBBBBB.XBXBBBBBBBXBXBBBBBBBBXBBBBBBBBBBBBBB
0. 9 .BBBXBBBBBBBBBBBBBBBBBBBBBBBBBBB..BB..B.BBBBXBBBBBBBBBXXXBBBBBBBBBBBBBBB.BBBBB.B
0.10 .BBBBBBBBBBBBBBBBBBBBBBBBBBBB.BB.BBBBBBB.BB.XBBBBBBBBBXBBBBBBBBXBXBBBXBBBBBBB.B.
0.11 .BBBXBBBBBBBBBBBBBBBBBBBBBBBBBB..XB..B..BB..BXBBBBXBBBBXBXBBBBBBBBBBBBBBBX.....B
0.12 .BBBBBBBBBBBBBBBBBBXBBBBBBBB.BBBBB.B...B...BXBBBBBBBBBBXBBBXBBBBBBB.BXBBBB.BB..B
0.13 .BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.BBB......BBXBXXXBBBBBXBBBBBBBBBBBBBB.BBBBBBB.
0.14 .BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.BBB.BBB.BBBBBBBBXBBBBBBBBBBBBBBBBBB.BBB.B...
1. 0 .BBBBBBBBBBBBB.BBBBBB..B.B....B...B.........BBBBBBBBBBBB.B.B..B....B............
1. 1 .BBBBBBBBXBBB.BBBBB.BBBBBB..................BBBBBBBBBBBBBBBBB.B..B.B.B..........
1. 2 .BBBBBBBBBBBBBBBBBBB.B.BB.BB..B....B........BBBBBBBBBBBXBBBB.BBBBBB..BB.........
1. 3 .BBBBBBBBBBBB.BBBBBB.BBBBB.B.BB........B....BBXBBBBBBBBBBBBBBBB.B.BX..B.........
1. 4 .BBBBBBBBBBBBBBBBBBBBB..BB.BBB.BB..........BBXBBBBBBBBBBBXBBBB.BBBB.B....B......
1. 5 .BBBBBBBBBBBBBBBBB....BB..BBB......B........BBXBBBBBBBBBBXBBB.BB..BBBB..........
1. 6 .BBBBBBBBBBBBBBBBB..BB..BB....B.............BBBBBBBBBBBBB.XBBBB.B.B..BBB........
1. 7 .BBBBBBBBBBBBBB.BB.B....B..B.B.....BB.......BBBBBBBBXBBBXBBBBB..BB..............
1. 8 .BBBBBBBBBBBXBBBBBB..B..BBBBBB......B.......BBBBBBXBBBBBBBBBBBBBBBB.B...........
1. 9 .BBBBBBBBBBBBBBBBBBBBBBBB..B.BB...B.........BBBBBBBBBBBB.BBBBB.B.BB.B...........
1.10 .BBBBBBBB.BBBBBBBBBBBB..B..B..B......BB.....BBBBBBBBBBBBBBBB.BB.BBB..BBBB.......
1.11 .BBBBBBBBBBBB.BB.BBBBB.B...B.B..............BBBBBBBBBBBB.BBB.BBBB.B...B.........
1.12 .BBBBBBBBBBB.BBBBBBBB.BB.B....B.............BBBBBBBBBBBBBBB...B....B.BBB........
1.13 .BBBBBBBBBBB.B.BBBBBBBBB....................BBBBBBBBBB.BBBBBBBBBBBBBB...........
1.14 .BBBBBBBBBBBBBBBBB.B.B..B.....B.............BBBBBBBBBB..B.BB..B.BB..............
Good sectors: 642/2400 (26%)
Missing sectors: 107/2400 (4%)
Bad sectors: 1651/2400 (68%)
80 tracks, 2 heads, 15 sectors, 512 bytes per sector, 1200 kB total
```
not sure why it is like this.

**Comment by davidgiven** [comment] 2019-04-08 10:06
Can you send me the HD flux file?

It's correctly guessed the clock, and it's identified about the right number of records so it's correctly detected the marker bytes at the beginning of each record, but it seems very suspicious that _not one_ sector header record passed CRC...

**Comment by tingox** [comment] 2019-04-08 10:38
sure, sent.

**Comment by tingox** [comment] 2019-04-08 12:05
Actually, I'm having quite good results decoding 5.25 inch, HD, ms-dos formatted floppies - _without_ the '--hd' flag.. I've tried a number of floppies on two different drives now, and I typically get better than 85% good sectors. Example:
```
tingo@kg-bsbox:~/personal/projects/psoc/fluxengine/tmp$ ../.obj/fe-readibm --retries=0 -o 525-CIS-pkunzip_ju-475.img -f 525-CIS-pkunzip_ju-475.flux
[..]
H.SS Tracks --->
0. 0 .BBBBBBBBBB..BB......B.B....B...................................................
0. 1 .BBBBBBBBBB..BB.B....B.B...BB...................................................
0. 2 .BBBBBBBBBB..BB.B....BBB...BB...................................................
0. 3 .BBBBBBBBBB..BB.B....BBB........................................................
0. 4 .BBBBBBBBBB..BB.B....BBB...B....................................................
0. 5 .BBBBBBBBBB..BB......BBB...B....................................................
0. 6 .BBBBBBBBBB..BB.B....BBB...BB...................................................
0. 7 .BBBBBBBBBB..BB.B....BBB...BB...................................................
0. 8 .BBBBBBBBBB..BB.B....BB....BB...................................................
0. 9 .BBBBBBBBBB..BB.B....BBB...BB...................................................
0.10 .BBBBBBBBBB..BB.B....BBB....B...................................................
0.11 .BBBBBBBBBB..BB.B....BBB...B....................................................
0.12 .BBBBBBBBBB..BB.B....BBB...B....................................................
0.13 .BBBBBBBBBB...B.B....B.....BB...................................................
0.14 .BBBBBBBBBB..BB.B....BBB...BB...................................................
1. 0 ...B.B...B......................................................................
1. 1 ...B.BBB.B......................................................................
1. 2 .B.B............................................................................
1. 3 .B...BB.........................................................................
1. 4 .B.B.BB.........................................................................
1. 5 .B.B.BBBBB......B...............................................................
1. 6 ...B.BBBBB......................................................................
1. 7 .B.B.BBB.B......................................................................
1. 8 .B.B.BB.B.......................................................................
1. 9 .B.B.BBBBB......B...............................................................
1.10 .B.B..BBBB......................................................................
1.11 .B.B..BB.B......................................................................
1.12 .B.B.....B......B...............................................................
1.13 .B.B.B..........................................................................
1.14 .B.B.....B......................................................................
Good sectors: 2075/2400 (86%)
Missing sectors: 0/2400 (0%)
Bad sectors: 325/2400 (13%)
80 tracks, 2 heads, 15 sectors, 512 bytes per sector, 1200 kB total
```
hope this helps.

**Comment by davidgiven** [comment] 2019-07-11 16:13
Duplicate: #46

**Comment by davidgiven** [comment] 2019-07-11 16:13
Duplicate of: #46

**Comment by davidgiven** [comment] 2019-07-11 16:14
Duplicate of #46

**Closed by davidgiven** 2019-07-11 16:13 UTC
