### ISSUE TITLE
5¼" hard-sectored 100 TPI CP/M floppies for Vector 4

### ISSUE THREAD

**Issue by ejona86** [davidgiven/fluxengine#187] opened 2020-09-12 22:04 UTC
I have a working Vector 4 made by Vector Graphics Inc in the early 1980s. It uses a 5¼" 16 hard sector sector floppy with 256 byte sectors and 100 TPI, I believe. The user guide claims a capacity of 630 KB which would mean 77 tracks (although [I see](http://retrotechnology.com/herbs_stuff/d_micropolis.html) a reference to an 80 track floppy being used as 77). The disk drive itself has a sticker that says "100 TPI DSR," although we purchased 96 TPI floppies to use with it. Earlier versions of the Vector seemed to use the Micropolis floppy disk controller and I think this one is probably compatible, so 100 TPI makes sense. This [brochure for Micropolis](https://web.archive.org/web/20170325221014/https://amaus.net/static/S100/micropolis/brochure/micropolis%20metafloppy.pdf) would make me believe it probably uses MFM encoding.

I've dug into CP/M and am semi-close to getting disk images using the Vector 4 itself. Getting images of the majority of the data is fairly easy, but reading the system track is more difficult and I'm still working on that. With a bit of work I can also dump the CP/M disk parameter header+block that has things like logical to physical sector mapping, logical sectors per track, and reserved system tracks. I'd be able to write a custom pattern to the disk, except for the system track.

What is the best way to go about getting these disks readable with fluxengine? The ds990 encoder looks like it was reasonably straight-forward, although I'd definitely need to guess-and-check and would need to consult a hard-sectored decoder. `fluxengine rpm` shows 6000 rpm, which is weird as I'd expect it to be closer to 5100 rpm (300 * 17, for 16 sector holes + 1 index hole). But it does seem to be at least semi-working as 6000 isn't completely outrageous and `inspect --dump-flux` isn't all zeros.

I've got the original Vector 4 floppy drive and a DOS-era floppy drive that seem to be working with fluxengine. Given the 100 TPI, it would seem that I need to use the original Vector 4 floppy drive and not the DOS-era one. Does that sound right?

**Comment by davidgiven** [comment] 2020-09-12 22:55
Yes, you're completely right about needing to use the original Vector 4 drive. 100TPI disks can't be read on 96TPI drives and vice versa. (Also, FWIW, the only difference between blank 100TPI _floppies_ and 96TPI floppies is the label.)

I'd say the first port of call is to try and hook the drive up to a FluxEngine. I've never seen or worked with a Micropolis drive and I don't know what the pinout is, but it's most likely easily adaptable. Someone out there probably has an adapter. Once you can reliably read and write PC disks you're probably good to go. There is already rather rudimentary support for hard-sector disks; see https://github.com/davidgiven/fluxengine/blob/master/arch/zilogmcz/decoder.cc for an example. That's an 8" format, but it shouldn't make a difference. One day I would like to add firmware support for detecting hard-sector disks and figuring out which pulse is the index hole, but right the decoder can't tell the difference between hard-sector pulses and index pulses so the decoder software just decodes everything it sees which seems to be a sector and puts it all together later. (If the Vector 4 disk format has a proper ID mark at the beginning of sectors, then you can just ignore the index holes completely --- they allow sectors to be identified from the flux pattern alone. The Zilog MCZ doesn't do that, so the decoder needs the index hole to know where a sector start; but the AES Lanier disk format does, which makes things a lot simpler. See https://github.com/davidgiven/fluxengine/blob/master/arch/aeslanier/decoder.cc.)

The Vector comes from an era where the on-disk encoding is probably documented somewhere. Reverse engineering the low-level format is fiddly but not hard, but reverse engineering the checksum _is_ hard, so if you can find this in the documentation it'll save loads of time!

Re the rpm result: were you by any chance putting the Victor disk in a modern 5.25" drive? If so, they spin at 360rpm, which would give a result of 6120 rpm.

**Comment by ejona86** [comment] 2020-09-13 01:00
I already have the old Vector floppy drive working with FluxEngine. It uses the standard floppy connector. I was so very happy when I realized it did; I had no such luck for the hard drive as it predates IDE.

Okay, so I should plug in the Vector floppy drive to a PC and format a disk. Then I can use FluxEngine to read it and make sure things are good. Very doable.

I've not found the disk encoding documented anywhere... yet. I'm confident it isn't in any of the Vector 4 manuals. Yeah, I'm most concerned about the checksum. I just found [Micropolis 1084 documentation](http://www.bitsavers.org/pdf/micropolis/metafloppy/1084-01_1040_1050_Users_Manual_Apr79.pdf) which in section 6-5 details the format. Hopefully it is similar. If not, I might get lucky and the checksum is implemented in software; I could dig through the CP/M driver and reverse engineer it.

If that Micropolis documentation matches my floppies, then the sector format is 40 zeros, one 0xFF, track+sector number, data, then checksum. And the checksum is an actual sum.

**Comment by ejona86** [comment] 2020-09-13 01:20
Oh, I forgot to mention, both the Vector and DOS floppy drives had the 6000 RPM. Although maybe half the time the Vector one returns 5454.55 RPM.

**Comment by davidgiven** [comment] 2020-09-13 10:27
Oh, awesome --- that's about half the hard work already done.

Looking at the Micropolis 1084 docs... this format looks rather similar to the Zilog MCZ format, with the same sync pattern.

You should be able to get a raw dump of the disk with:

`fluxengine read ibm --write-flux=micropolis.flux --retries=0 -s :t=0-76`

It won't successfully decode any sectors, but you will get an output flux file which would allow development without needing the drive hooked up. Is there any chance you could do this and send it to me so I can have a look?

**Comment by ejona86** [comment] 2020-09-13 21:31
So I've been poking at it for a while. I think I follow most of what's going on with fluxengine and a decoder, except what I think is some clock detection magic via seekToPattern. I have successfully gotten index vs sector hole detection working. At this point I just throw away the sector that has the index hole.

I'm using `--revolutions 21` (17*1.25) to get an entire track, otherwise it seems it only dumps a single sector due to all the "index" holes. I first did `--index-mode=1` and it did get more data that `0`, but the index holes were looking helpful for reverse engineering.

I've attached two flux files in [micropolis.zip](https://github.com/davidgiven/fluxengine/files/5215091/micropolis.zip). micropolis-21.flux is a "blank" formatted disk. The format utility showed some errors on track 45 and greater, so ignore those tracks. test-21.flux has about 8 files named test.txt, test2.txt, test3.txt, ... that each contain "test\r\n" 255 times. Formatting showed lots of errors after track 4, largely on head 1, but the files generally appeared to be readable after writing. Track 23 is the first error with head 0; tracks 5-7, 11, 13, 15-20 have errors with head 1. I can work on finding better floppies, but this seemed enough for initial investigation.

I'm concerned the hard sectors are confusing timings. I know it confuses the RPM, but could it be causing other trouble? The clock detection histogram looks pretty strange.

```
Reading from: micropolis-21.flux:d=0:s=0:t=0
  0.0: 209.221 ms in 58944 bytes
0xe640 bytes of data in 209.221ms
Required USB bandwidth: 275.127kB/s

Clock detection histogram:
 73 6.08    381 ██▉
 74 6.17   2051 ████████████████ 
 75 6.25   4714 ████████████████████████████████████▉
 76 6.33   5109 ████████████████████████████████████████ 
 77 6.42   2886 ██████████████████████▌
 78 6.50    940 ███████▎
 79 6.58     79 ▌
...
 92 7.67    134 █ 
 93 7.75    552 ████▎
 94 7.83   1371 ██████████▋
 95 7.92   1228 █████████▌
 96 8.00    576 ████▌
 97 8.08    124 ▉
...
 110 9.17     63 ▍
 111 9.25    324 ██▌
 112 9.33    725 █████▋
 113 9.42    777 ██████ 
 114 9.50    869 ██████▊
 115 9.58    716 █████▌
 116 9.67    209 █▋
...
 126 10.50     60 ▍
 127 10.58    237 █▊
 128 10.67    413 ███▏
 129 10.75    672 █████▎
 130 10.83    834 ██████▌
 131 10.92    767 ██████ 
 132 11.00    482 ███▊
 133 11.08    178 █▍
...
Noise floor:  51
Signal level: 255
Peak start:   72 (6.00 us)
Peak end:     80 (6.67 us)
Median:       76 (6.33 us)
6.33 us clock detected.
```

As a clue to where the test.txt files may be stored, the [Vector programmers guide](https://archive.org/details/bitsavers_vectorGrapector4CPMProgrammersGuideSep82_18049374) on 3-52 has exhibit 3-2 which describes the reservations for double-sided floppies.

```
records per track: 32
records per sector: 2
blocks for directory: 2
reserved tracks: 4
records per block: 16
```

"Record" there is a CP/M 128 byte record. So 4 tracks are system tracks and one track is directory information.

**Comment by ejona86** [comment] 2020-09-22 04:28
I was able to read the floppies from CP/M and dump them, including system tracks. I've attached them as [micropolis-img.zip](https://github.com/davidgiven/fluxengine/files/5259146/micropolis-img.zip) (even though I suspect at this point it is unrelated to Micropolis, I kept the naming to match the flux).

"test.raw" has tracks 0-24 (I think that's 12 tracks with 2 sides, plus half another track), with 6 (track 3, side 1) and 23 failed to read. "micropolis.raw" has tracks 0-64, where 48, 56, 61, 63, and 64 failed to read. But really, it has a very small bit of code in the system tracks to print out it isn't a boot floppy and the rest is 0xE5.

**Comment by davidgiven** [comment] 2020-09-22 19:00
Sorry, I forgot all about this! I've investigated the flux files --- thanks, you test images were really useful. I don't think it's Micropolis 1084. The structures on the disk don't look right, as I can see a sector header and sector data record, and the Metropolis format doesn't have one.

One weird thing is that if I look at data on track 60, I see repeated patterns of X-X--X--X-X--X--X-X--X--X-X. This should encode as repeated E5. The thing is, E5 has a bit pattern of 1110-0101, and I can't make that match. It's not FM or MFM. I wonder if this thing uses some awful GCR variant? This _can_ be figured out, I did it with the Brother, but it's really painful...

If you could make one, what would be really useful is a flux file containing a complete track of 0x00, 0x00, 0xff, 0xff, 0x00, 0x00, etc; and a complete track of 0x00, 0x01, 0x02, 0x03 etc. That might give me more of a clue as to what's going on here.

**Comment by ejona86** [comment] 2020-09-27 01:57
I wrote a test disk and dumped the flux twice. I've [attached the results](https://github.com/davidgiven/fluxengine/files/5287589/pattern.zip). There's 8 test patterns, one per track and both sides have same data. I've not yet looked looked at the bits to see if anything jumps out.

I wondered if the ugly histogram was due to the machine not writing near sector holes, so I half-heartedly took a magnet to the disk before writing. I had some false-starts when writing, so it was written multiple times post-magnet. The histogram for the early tracks look good, but the later tracks still have the strange timing.

**Comment by ejona86** [comment] 2020-09-28 03:27
I've dug into the flux, and I don't trust what I'm seeing. The two sides of the floppy don't really seem to match and the flux still doesn't make sense. I'm really not trusting the clocks. I expect at some point I'll need to dig in and understand how the decoder determines the clock.

I think I'll try cleaning/swapping out the floppy drive (as I have two) and maybe creating different test floppy. Maybe something isn't using CHS data order.

I've found dumping the index holes to be helpful:
```patch
diff --git a/src/fe-inspect.cc b/src/fe-inspect.cc
index 012de08..16c7ee4 100644
--- a/src/fe-inspect.cc
+++ b/src/fe-inspect.cc
@@ -259,11 +259,23 @@ int mainInspect(int argc, const char* argv[])
 
 	if (dumpBitstreamFlag)
 	{
+		auto curPos = fmr.tell();
+		fmr.seekToIndexMark();
+		auto nextIndex = fmr.tell();
+		fmr.seek(curPos);
+
 		std::cout << fmt::format("\n\nAligned bitstream from {:.3f}ms follows:\n",
 				fmr.tell().ns() / 1000000.0);
 
 		while (!fmr.eof())
 		{
+			if (fmr.tell().ns() > nextIndex.ns()) {
+				std::cout << "----- index -----\n";
+				curPos = fmr.tell();
+				fmr.seekToIndexMark();
+				nextIndex = fmr.tell();
+				fmr.seek(curPos);
+			}
 			std::cout << fmt::format("{:06x} {: 10.3f} : ",
 				fmr.tell().bytes, fmr.tell().ns() / 1000000.0);
 			for (unsigned i=0; i<50; i++)
```

**Comment by davidgiven** [comment] 2020-09-28 21:40
You're right, something is decidedly peculiar here. The flux data doesn't seem to match up with the raw image data. I see from the patterns in the raw file that one track is 8kB, so that must be spanning both sides, but as you say the data doesn't match on each side. I thought for a while it might be using a HCS rather than CHS format, with the tracks going all the way up one side before moving to the other side, but that doesn't fit either.

I can confirm that the distribution of intervals is all wrong, too. Track 5 has a big peak at 7us and a smaller one at 9us. But that should never happen. For FM, the peaks should be a factor of two apart, and for MFM they should be a factor of two apart of half the smallest peak. I would expect to see a peak at 7us and another peak and 10.5us, representing X-X and X--X intervals. That doesn't even match GCR.

Two questions come to mind:

- which FluxEngine firmware are you using? Earlier this year I fixed a bug which caused data corruption. It shouldn't apply here, though, but it's still worth checking.
- do you know the drive you're using with the FluxEngine works? Could you try swapping it with the one in the Vector 4? Other things that are worth trying is to use `fluxengine writetestpattern` to write regular pulses to the disk, and then read them back and see if they look reasonable.

On the other hand the data is incredibly regular and fairly noise-free, which doesn't point at a bad drive...

(I would also like to send a small curse back to the Vector Graphics founders for coming up with a name so impossible to search for. Hadn't they even _heard_ of Google?)

**Comment by ejona86** [comment] 2020-09-30 04:29
We have a winner! I'll note that `rpm` for this different drive gives 5000, 4615, or 10000 rpm.

The flux: [pattern-drive2.zip](https://github.com/davidgiven/fluxengine/files/5303058/pattern-drive2.zip). read1/2 are just 8 tracks. read3 is the full floppy.

It does seem the floppy program I used interpreted the input as HCS, so the broken drive is working halfway, as I saw that rough pattern in the flux.

The format is MFM with each sector:
```
00 .. 00 FF tt ss 00 00 00 00 00 00 00 00 00 00 data-256 sum ?? ?? ?? ?? AA 00 .. 00
```

Track and sector are zero-indexed. The checksum includes the track and sector. The checksum is a sum including carries; equivalently, it is a 16 bit checksum with the two bytes added together. After I figured that out manually I realized it is very similar to the Micropolis format...

I don't know what the next 4 bytes are and they don't exist in the Micropolis format. I tried CRC16-CCITT and didn't see anything jump out.

I've been able to make a decoder. Looks pretty good for this known-bad disk:
```
Autodetecting output geometry
H.SS Tracks --->
0. 0 .............................................................................
0. 1 .............................................................................
0. 2 .............................................................................
0. 3 .............................................................................
0. 4 .............................................................................
0. 5 .............................................................................
0. 6 .............................................................................
0. 7 ........................................................B....................
0. 8 .............................................................................
0. 9 ....................................................B............BB.B...B..B.
0.10 ..............................................B........BB.BB.BB.BBB..B...BBBB
0.11 ...............................................B.............................
0.12 .............................................................................
0.13 .............................................................................
0.14 .............................................................................
0.15 .............................................................................
1. 0 B............................................................................
1. 1 .............................................................................
1. 2 .............................................................................
1. 3 .............................................................................
1. 4 .............................................................................
1. 5 .............................................................................
1. 6 ........................................................B.B..BBBB........BBBX
1. 7 .......B......................BBBBB................BB............BB...BBBB.BX
1. 8 ................................................B........................BBBX
1. 9 .................................BC...........................B.BBBBBBBBBBBBB
1.10 ....................................B.B.............B..B.BBB....B.......BBBB.
1.11 ................................................XXBBX.B......................
1.12 .............................................................................
1.13 .............................................................................
1.14 .............................................................................
1.15 ..........................................................C..................
Good sectors: 2374/2464 (96%)
Missing sectors: 6/2464 (0%)
Bad sectors: 84/2464 (3%)
writing 77 tracks, 2 heads, 16 sectors, 256 bytes per sector, 616 kB total
```

**Comment by davidgiven** [comment] 2020-09-30 08:42
Oh, fantastic. So, it _was_ a drive issue, although a really odd one.

I did get hold of a Vector 4 flux image yesterday, and got up to the point of trying to figure out the checksum, but you beat me to the rest of it. I did try summing all the bytes but the result didn't match; the Micropolis docs said to sum everything including the two header bytes. Which ones are you using?

(Also, friends don't let friends use simple addition as checksums.)

The run of 0s between the header and the data is apparently because the 1084 format defines 266 byte sectors. It's possible that this is some kind of metadata field, but until we find something that actually uses it it's probably safe to ignore.

If you can put together a simple PR I'll clean it up and merge it in --- it doesn't need to be perfect.

**Comment by ejona86** [comment] 2020-09-30 14:10
Oh, right, it did say 266 bytes. Great. So Vector 4 is still an extension of the Micropolis format. I was thinking the AA looked like a flag that would normally be 00 and the Vector extended the Micropolis format. I did check, and the mystery 4 bytes don't even appear to be CRC32.

Looks like this is still a Micropolis format: https://deramp.com/downloads/polymorphic/poly-88/software/Micropolis%20CPM/Disk%20Image%20Transfer/ReadMe.pdf . Maybe we can find some later Micropolis documentation. It confirms that it was common for CP/M to not use the _first_ 10 bytes of payload, so this doesn't seem like some custom Vector thing. It says the 4 bytes are ECC, but I can't find any technical specification of the ECC used. I see the Intel 8089 had some ECC (although a quick search showed no details); I may need to look at the controller board to figure out what chip was doing the ECC. Something for later.

What should I call this decoder? It seems Micropolis is actually still an accurate name. The 10-unused bytes is the only real variable it seems. I'll try to send a PR later this week.

The checksum is a simple sum of all data and sector and track, _with carry_.

Starting just after the sync FF:
```
00000 : 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00010 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00020 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00030 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00040 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00050 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00060 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00070 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00080 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00090 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
000a0 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
000b0 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
000c0 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
000d0 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
000e0 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
000f0 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  : ................
00100 : 00 00 00 00 00 00 00 00 00 00 00 00 05 56 9d 65  : .............V.e
00110 : bd aa -- -- -- -- -- -- -- -- -- -- -- -- -- --  : ..
```

This is track 0, sector 5. I sum the `tt ss` along with the 266 bytes of data. Here the sum is obviously 5 and matches the checksum at the end.

```
00000 : 06 0d 00 00 00 00 00 00 00 00 00 00 01 01 01 01  : ................
00010 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
00020 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
00030 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
00040 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
00050 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
00060 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
00070 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
00080 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
00090 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
000a0 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
000b0 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
000c0 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
000d0 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
000e0 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
000f0 : 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  : ................
00100 : 01 01 01 01 01 01 01 01 01 01 01 01 14 21 6c 99  : .............!l.
00110 : c6 aa -- -- -- -- -- -- -- -- -- -- -- -- -- --  : ..
```

So here the on-disk checksum is 0x14. We have 256 ones so the sum will overflow once. 0x06+0x0d=0x13, but we need to add one more for the carry when it overflowed. For my actual code I compute a 16 bit checksum and add the two bytes together at the end.

**Comment by davidgiven** [comment] 2020-09-30 22:53
Ah, I'd missed that propagating the carry flag was important.

Let's call this the micropolis format. I strongly suspect that all Micropolis disks use minor variations of the same format (number of payload bytes, size of checksum...) all of which are easily configurable at run time using flags, should the need arise.

**Closed** 2020-10-11 16:52 UTC
